<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>ASS_Editor</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		 <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="ImGui.NET" Version="1.91.6.1" />
		<PackageReference Include="ImGui.NET.Docking" Version="1.75.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Raylib-cs" Version="7.0.0" />
	</ItemGroup>
	
	<ItemGroup>
		<None Update="assets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="workspaces\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="workspaces\" />
	</ItemGroup>
</Project>
